name: "Push ecr"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  pkg:
    name: Push to ecr
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 2
        # Fetch submodules
        submodules: recursive
    - name: setup go
      uses: actions/setup-go@v3.4.0
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      env:
        BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
      with:
        role-to-assume: ${{ secrets.ECR_ROLE_ARN }}
        role-session-name: Push-${{ github.ref_name }}
        aws-region: ${{ secrets.ECR_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: ${{ secrets.ECR_REPO_NAME }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
